config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :products
  resources :services

  root to: 'pages#home'

  get 'about', to: 'pages#about'
  get 'faq', to: 'pages#faq'
  get 'contact', to: 'pages#contact'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  
end

app/models/product.rb
class Product < ApplicationRecord

  validates_presence_of :title, :brand, :price
  
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include DeviseWhitelist

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :start_time)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do 
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def faq
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout 'product'
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :brand, :price, :image)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = Service.all  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


  def copyright_generator
    AslViewTool::Renderer.copyright 'ASL Salon', 'All rights reserved'
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def image_generator(height:, width:)
    "http://via.placeholder.com/#{height}x#{width}"
  end

  def product_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :appointment_name %>
  </div>

  <div class="field-group">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :appointment_start_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Appointments</h1>
  <div class="row">
    <div class="col-sm-8">
      <%= month_calendar do |date| %>
        <%= date %>
      <% end %>
    </div>

    <div class="col-sm-4">
      <div class="card app-list"> 
        <% @appointments.each do |appointment| %>
          
          <p><%= appointment.name %></p>
          <p><%= appointment.start_time %></p>
          <p><%= link_to 'Show', appointment %></p>
          <p><%= link_to 'Edit', edit_appointment_path(appointment) %></p>
          <p><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          
        <% end %>
      </div> 
    </div>
  </div>
</div>
<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<div class='container'>

  <h1>New Appointment</h1>

  <div class='row'>
    <div class='col-md-8'>

      <%= render 'form', appointment: @appointment %>

    </div>

    <div class='col-md-4'>

    </div>
  </div>
  <%= link_to 'Back', appointments_path, class: 'btn btn-primary btn-block' %>
</div>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <meta name="keywords" content="<%= @seo_keywords %>" />
    <link href="https://fonts.googleapis.com/css?family=Averia+Serif+Libre" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/css/bootstrap.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container"> -->
          <%= render "shared/application_nav" %>

          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

          <%= yield %>

          <%= render "shared/application_footer" %>
        <!-- </div>
      </div>
    </div> -->  

  </body>
</html>

app/views/layouts/product.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Averia+Serif+Libre" rel="stylesheet">
    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag 'products', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    
    <%= render 'shared/product_nav' %>

    <%= yield %>
    
    <%= render 'shared/product_footer' %>

  </body>

</html>

app/views/pages/about.html.erb
<div class="app-card-container">
  <div>
    <h1><span class="about-title">ASL Salon</span></h1>

    <div class="row">
      <div class="col-md-4">
        <p>Something Here</p>

      </div>

      <div class="col-md-8">
        
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="app-card-container">
  <div>

    <h1>Contact</h1>

    <hr>
    <div class="row">
      <div class="col-md-6">
        <h3>Address</h3>

        <p>218 W. 1700 N.</p>
        <p>Lehi, UT</p>

        <h3>Phone</h3>

        <p><%= number_to_phone "801-560-3642" %></p>

        <h3>Email</h3>

        <p>romanlavery@gmail.com</p>
      </div>

      <div class="col-md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3037.9700235667433!2d-111.85702130679216!3d40.409514852901424!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sus!4v1515209778619" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

app/views/pages/faq.html.erb
<h1>What would you like to know?</h1>

app/views/pages/home.html.erb
<main role="main" class="inner cover">
  <h1 class="cover-heading">ASL Salon</h1>
  <% if current_user %>
    <h3>Hi, <%= current_user.first_name %></h3>
  <% end %>
  <p class="lead">Come make yourself the most beautiful person the world has ever seen!</p>
  <p class="lead">
    <%= link_to "Learn More", about_path, class: "btn btn-lg btn-secondary" %>
  </p>
  
</main>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :product_brand %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image, id: :product_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="product-lead">
  <h1>Products</h1>
</div>
<div class="album text-muted">
  <div class="container">
    <div class="product-index">
      <div class="row">
        
        <% @products.each do |product| %>
          <div class="col-md-4">
            <p><%= link_to "#{product.title}", product %></p>
            <p><%= image_tag product.image, width: '50%' %></p>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

<br>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container product-container">
  <div class='row'>
    <div class="col-md-7">
      <%= image_tag @product.image, width: '75%' %>

    </div>
    <div class="col-md-5">
      <h1><%= @product.title %></h1>


      <p>
        <%= @product.brand %>
      </p>

      <p>
        <%= "$%.2f" % @product.price %>
      </p>



      <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-primary" %> |
      <%= link_to 'Back', products_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/services/index.html.erb
<h1>Services</h1>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a href="#" class="brand">Project name</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <a href="#">2-level Dropdown <i class="icon-arrow-right"></i></a>
                <ul class="dropdown-menu sub-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li class="nav-header">Nav header</li>
              <li><a href="#">Separated link</a></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form action="" class="navbar-search pull-left">
          <input type="text" placeholder="Search" class="search-query span2">
        </form>
        <ul class="nav pull-right">
          <li><a href="#">Link</a></li>
          <li class="divider-vertical"></li>
          <li class="dropdown">
            <a class="#" href="#">Menu</a>
          </li>
        </ul>
      </div>
      <!-- /.nav-collapse -->
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="container nav">
  <%= link_to "Home", root_path %>
  <%= link_to "About", about_path %>
  <%= link_to "Contact", contact_path %>
  <%= link_to "FAQ", faq_path %>
  <%= link_to "Products", products_path %>
</div>

app/views/shared/_product_footer.html.erb
<footer class="mastfoot">
  
  <div class="container">
    <span class="footer-copy"><%= copyright_generator %></span>
    
    <span class="float-right footer-buttons">
      <%= link_to "View all Products", products_path, class: "btn btn-primary" %> /
      <a href="#" class = 'btn btn-primary'>Back to top</a>
    </span>
  </div>
  
</footer>

<!-- <footer class="mastfoot">
  <div class="inner"> -->

app/views/shared/_product_nav.html.erb
<header class="masthead clearfix">
  <div>
    <h3 class="masthead-brand">ASL Salon</h3>
    <nav class="nav nav-masthead prod-nav">
      <a class="nav-link active hnav "><%= link_to 'Home', root_path %></a>
      <a class="nav-link hnav"><%= link_to 'About', about_path %></a>
      <a class="nav-link hnav"><%= link_to 'Contact', contact_path %></a>
      <a class="nav-link hnav"><%= link_to "FAQ's", faq_path %></a>
      <a class="nav-link hnav"><%= link_to 'Products', products_path %></a>
      <a class="nav-link hnav"><%= link_to 'Appointments', appointments_path %></a>

      <% if current_user %>
        <a class="nav-link hnav"><%= link_to "Logout", destroy_user_session_path, method: :delete %></a>
      <% else %>
        <a class="nav-link hnav"><%= link_to "Login", new_user_session_path %></a>
        <a class="nav-link hnav"><%= link_to "Register", new_user_registration_path %></a>
      <% end %>
    </nav>
  </div>
</header>